---
pipeline: Batch_7
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: false
    file: <metadata file name>
    merge_column: <Column to merge on>
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: true
feature_select:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: true
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : false
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2024_01_23_Batch_7
plates:
  - name: 2024_01_17_B7A1R1_P1T1
    process: true
  - name: 2024_01_17_B7A1R1_P1T2
    process: true
  - name: 2024_01_17_B7A1R1_P1T3
    process: true
  - name: 2024_01_17_B7A1R1_P1T4
    process: true
  - name: 2024_01_17_B7A1R1_P2T1
    process: true
  - name: 2024_01_17_B7A1R1_P2T2
    process: true
  - name: 2024_01_17_B7A1R1_P2T3
    process: true
  - name: 2024_01_17_B7A1R1_P2T4
    process: true
  - name: 2024_01_18_B7A1R1_P3T1
    process: true
  - name: 2024_01_19_B7A1R1_P3T2
    process: true
  - name: 2024_01_19_B7A1R1_P3T3
    process: true
  - name: 2024_01_19_B7A1R1_P3T4
    process: true
  - name: 2024_01_19_B7A1R1_P4T1
    process: true
  - name: 2024_01_23_B7A1R1_P4T2
    process: true
  - name: 2024_01_22_B7A1R1_P4T3
    process: true
  - name: 2024_01_22_B7A1R1_P4T4
    process: true
  - name: 2024_01_22_B7A2R1_P1T1
    process: true
  - name: 2024_01_22_B7A2R1_P1T2
    process: true
  - name: 2024_01_22_B7A2R1_P1T3
    process: true
  - name: 2024_01_23_B7A2R1_P1T4
    process: true
process: true
